import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
    route("login", "routes/login.tsx"),
    route("careers", "routes/careers.tsx"),
    route("election-management", "routes/election-page.tsx"),
    route("nprweek2026", "routes/nprweek2026.tsx"),
    route("DevbhoomiAISummit", "routes/DevbhoomiAISummit.tsx"),
    route("UISHackathon", "routes/hackathon-legacy-redirect.tsx"),
    route("DevbhoomiAISummit/nomination", "routes/devbhoomi-ai-nomination.tsx"),
    route("DevbhoomiAISummit/delegate-pass", "routes/devbhoomi-ai-delegate-pass.tsx"),
    route("UKISHackathon", "features/hackathon/Layout.tsx", [
        index("features/hackathon/pages/Home.tsx"),
        route("problems", "features/hackathon/pages/Problems.tsx"),
        route("problems/:id", "features/hackathon/pages/ProblemDetail.tsx"),
        route("register/solution", "features/hackathon/pages/RegisterSolution.tsx"),
        route("register/mentor", "features/hackathon/pages/RegisterMentor.tsx"),
        route("solutions", "features/hackathon/pages/Solutions.tsx"),
        route("mentors", "features/hackathon/pages/Mentors.tsx"),
        route("terms-and-conditions", "features/hackathon/pages/TermsAndConditions.tsx"),
        route("admin/sign-in", "features/hackathon/pages/AdminSignIn.tsx"),
        route("admin", "features/hackathon/pages/AdminDashboard.tsx"),
        route("*", "features/hackathon/pages/NotFound.tsx"),
    ]),
    index("routes/app.tsx"),
    // route("signup", "routes/signup.tsx"),
    layout("routes/protected-layout.tsx", [
        route("dashboard", "routes/home.tsx"),
        route("candidates", "routes/candidates.tsx"),
        route("voters", "routes/voter-list.tsx"),
        route("voters/:id", "routes/voter-profile.tsx"),
        route("constituency", "routes/constituency.tsx"),
        route("candidates/:id", "routes/candidate-profile.tsx"),
        route("elections", "routes/election.tsx"),
        route("parties", "routes/parties.tsx"),
        route("parties/:id", "routes/party-profile.tsx"),
    ]),
] satisfies RouteConfig;
